### ISSUE TITLE
Problems encountered by the simulator

### ISSUE THREAD

**Issue by 773146535** [ChihChiangHuang/AlbionFishingBot_LDPlayer#1]
Traceback (most recent call last):
  File "F:\下载\AlbionFishingBot_LDPlayer-main\AlbionFishingBot_LDPlayer-main\Main.py", line 121, in <module>
    stream=p.open(input_device_index=dev_idx,format=pyaudio.paInt16,channels=2,rate=44100, input=True, frames_per_buffer=1024)
NameError: name 'dev_idx' is not defined

**Comment by ChihChiangHuang** [comment]
Which means the program does not find your audio instrument. Edit the code yourself to run this Python script

**Comment by 773146535** [comment]
我应该如何修改

**Comment by ChihChiangHuang** [comment]
You should find a Python tutor to help you.
